# Generated by Django 3.1.1 on 2020-11-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_activityentry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
