# Generated by Django 3.1.1 on 2020-11-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_activityentry_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityentry',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
