# Generated by Django 3.1.1 on 2020-11-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_activityentry_createtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityentry',
            options={'get_latest_by': 'createTime'},
        ),
        migrations.AddField(
            model_name='habit',
            name='dataType',
            field=models.SmallIntegerField(default=0),
        ),
    ]
