# Generated by Django 3.1.1 on 2020-11-12 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_auto_20201112_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='associatedHabit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dataSet', to='habits.habit'),
        ),
    ]
