# Generated by Django 3.1.1 on 2020-11-17 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_auto_20201117_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualitiativeDataSet',
            fields=[
                ('dataset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='habits.dataset')),
            ],
            bases=('habits.dataset',),
        ),
    ]
