# Generated by Django 3.1.1 on 2020-11-18 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0012_auto_20201117_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataentry',
            name='parentSet',
        ),
        migrations.AddField(
            model_name='qualitativedata',
            name='parentSet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dataEntries', to='habits.qualitativedataset'),
        ),
        migrations.AddField(
            model_name='quantitativedata',
            name='parentSet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dataEntries', to='habits.quantitativedataset'),
        ),
    ]
