# Generated by Django 3.1.1 on 2020-11-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='notificationCount',
            field=models.IntegerField(default=0),
        ),
    ]
