# Generated by Django 3.1.1 on 2020-11-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_activitylog_notificationcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityentry',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
