# Generated by Django 3.1.1 on 2020-11-11 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_auto_20201111_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityentry',
            name='status',
        ),
    ]
