# Generated by Django 3.1.1 on 2020-11-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_auto_20201112_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitiativedata',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quantitativedata',
            name='content',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
